<?php

class DownRowForm {
    protected $objPHPExcel;
    protected $objActSheet;
    protected $listArr=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];
    protected $row = 1;
    protected $sheetNum = 0;

    protected $endNum =0;
    protected $headList;
    protected $excelList = array();

    public $firmList=array();
    public $tableHeardList=array();

    protected $lbsMonth = 0;//總公司欠款月數
    protected $otherMonth = 0;//細公司欠款月數

    protected function headListTwo(){
        return array(
            "staff_id"=>array("name"=>Yii::t("several","assign staff"),"width"=>""),
            "salesman_id"=>array("name"=>Yii::t("several","salesman one"),"width"=>""),
            "payment"=>array("name"=>Yii::t("several","payment"),"width"=>""),
            "group_type"=>array("name"=>Yii::t("several","group type"),"width"=>""),
            "acca_username"=>array("name"=>Yii::t("several","accountant username"),"width"=>""),
            "acca_phone"=>array("name"=>Yii::t("several","accountant phone"),"width"=>""),
            "status_type"=>array("name"=>Yii::t('code','status type'),"width"=>""),
            "acca_fun"=>array("name"=>Yii::t("several","method"),"width"=>""),
            "acca_lang"=>array("name"=>Yii::t("several","accountant lang"),"width"=>""),
            "acca_fax"=>array("name"=>Yii::t("several","accountant fax"),"width"=>""),
            "refer_code"=>array("name"=>Yii::t("several","refer code"),"width"=>""),
            "usual_date"=>array("name"=>Yii::t("several","usual date"),"width"=>""),
            "head_worker"=>array("name"=>Yii::t("several","head worker"),"width"=>""),
            "other_worker"=>array("name"=>Yii::t("several","other worker"),"width"=>""),
            "advance_name"=>array("name"=>Yii::t("several","advance name"),"width"=>""),
            "listing_name"=>array("name"=>Yii::t("several","listing name"),"width"=>""),
            "listing_email"=>array("name"=>Yii::t("several","listing email"),"width"=>""),
            "listing_fax"=>array("name"=>Yii::t("several","listing fax"),"width"=>""),
            "new_month"=>array("name"=>Yii::t("several","new month"),"width"=>""),
        );
    }

    public function __construct() {
        $phpExcelPath = Yii::getPathOfAlias('ext.phpexcel');
        //spl_autoload_unregister(array('YiiBase','autoload'));
        include($phpExcelPath . DIRECTORY_SEPARATOR . 'PHPExcel.php');

        $this->objPHPExcel = new PHPExcel();
//设置文档基本属性
        $objProps = $this->objPHPExcel->getProperties();
        $objProps->setCreator("Zeal Li");
        $objProps->setLastModifiedBy("Zeal Li");
        $objProps->setTitle("Office XLS Test Document");
        $objProps->setSubject("Office XLS Test Document, Demo");
        $objProps->setDescription("kol document, generated by PHPExcel.");
        $objProps->setKeywords("office excel PHPExcel");
        $objProps->setCategory("Test");

        $this->objActSheet = $this->objPHPExcel->setActiveSheetIndex(0); //填充表头
        $this->objPHPExcel->getActiveSheet()->getDefaultStyle()->getFont()->setSize(12);      //字体大小
        //$this->objPHPExcel->disconnectWorksheets();
        //var_dump($this->objPHPExcel);die();
        //$this->objPHPExcel->getActiveSheet()->getStyle('A1:H8')->getBorders()->getRight()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);
    }

    //設置起始行
    public function setStartRow($num){
        $this->row = $num;
    }

    //設置某行的內容
    public function setRowContent($row,$str,$endRow=0){
        $this->objActSheet->setCellValue($row,$str);
        if(!empty($endRow)){
            $this->objActSheet->mergeCells($row.":".$endRow);
        }
    }

    //設置規則提示
    public function setRulesArr($arr){
        for ($i = 0;$i<count($arr);$i++){
            $this->objActSheet->setCellValue("A".($i+1),$arr[$i]);
            $this->objActSheet->getStyle( "A".($i+1))->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_RED);
        }
    }

    protected function setWidthToArr($arr,$width){
        if(is_array($arr)){
            foreach ($arr as $str){
                $str = strtoupper($str);
                $this->objPHPExcel->getActiveSheet()->getColumnDimension($str)->setWidth($width);
            }
        }else{
            $str = strtoupper($arr);
            $this->objPHPExcel->getActiveSheet()->getColumnDimension($str)->setWidth($width);
        }
    }

    //設置excel背景顏色 cellColor('A',"D6D6D6") cellColor('B2',"D6D6D6") cellColor('C3:D4',"D6D6D6")
    protected function cellColor($cells,$color){
        $this->objPHPExcel->getActiveSheet()->getStyle($cells)->getFill()->applyFromArray(array(
            'type' => PHPExcel_Style_Fill::FILL_SOLID,
            'startcolor' => array(
                'rgb' => $color
            )
        ));
    }

    /*
     * $heardArr=array()
     */
    //設置表頭
    protected function setRowHeard($dateTime="",$title="客戶詳情"){
        $dateTime = empty($dateTime)?"2019-09-02 14:40:45":$dateTime;
        $this->objPHPExcel->getActiveSheet()->setTitle($title);
        $this->objPHPExcel->getActiveSheet()->freezePane('D6');
        //3.填充表格
        $this->setWidthToArr(array("A","B","C"),20);

        $this->objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(14);         //第1行字体大小
        $this->objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(14);         //第2行字体大小
        //$this->objPHPExcel->getActiveSheet()->getRowDimension('7')->setRowHeight(30);    //第5行行高
        //設置基礎信息表頭
        $this->objActSheet->setCellValue('A1',"客戶欠款列表");
        $this->objActSheet->setCellValue('A2',"STATUS REPORT : ALL CUSTOMER");
        $this->objActSheet->setCellValue('A4',$dateTime);

        $row = 5;
        //設置客戶信息表頭
        $arrOne = array(Yii::t('several','Customer Code'),Yii::t('several','Customer Name'),Yii::t('several','Company Code'));
        foreach ($arrOne as $key=>$item){
            $str = $this->listArr[$key];
            $this->setRowContent($str.$row,$item);
        }
        $endNum = count($arrOne);
        //設置公司信息
        foreach ($this->firmList as $key =>$item){
            if(key_exists($key,$this->tableHeardList)){
                foreach ($this->tableHeardList[$key] as $value){
                    $str = $this->getStrToNum($endNum);
                    $this->setRowContent($str.$row,$item["name"]."\r\n".$value);
                    $this->objActSheet->getStyle($str.$row)->getAlignment()->setWrapText(true);
                    $this->setWidthToArr($str,15);
                    $endNum++;
                }
                $str = $this->getStrToNum($endNum);
                $this->setRowContent($str.$row,$item["name"]."\r\n".Yii::t("several","Amt"));
                $this->objActSheet->getStyle($str.$row)->getAlignment()->setWrapText(true);
                $this->setWidthToArr($str,15);
                $endNum++;
            }
        }
        //$endNum++;
        $str = $this->getStrToNum($endNum);
        $this->setRowContent($str.$row,"總公司\r\n欠款月數");
        $this->objActSheet->getStyle($str.$row)->getAlignment()->setWrapText(true);
        $endNum++;
        $str = $this->getStrToNum($endNum);
        $this->setRowContent($str.$row,"細公司\r\n欠款月數");
        $this->objActSheet->getStyle($str.$row)->getAlignment()->setWrapText(true);

        //設置客戶詳情
        $arrTwo = $this->headListTwo();
        foreach ($arrTwo as $key=>$item){
            $endNum++;
            $str = $this->getStrToNum($endNum);
            $this->setRowContent($str.$row,$item["name"]);
        }

        $this->row = 6;
    }

    //設置頁頭數組
    protected function setExcelTop(){
        $monthList = UploadExcelForm::getMonth();
        $firmList = array();
        $rows = Yii::app()->db->createCommand()->select()->from("sev_firm")
            ->where("id")->order("firm_type desc")->queryAll();
        foreach ($rows as $row){
            $this->firmList[$row["id"]] = array("name"=>$row["firm_name"],"type"=>$row["firm_type"]);
            if(empty($row["firm_type"])){
                $firmList[] = $row["id"];
            }
        }
        $this->firmList["branch"] = array("name"=>Yii::t("several","branch"),"type"=>0);//係公司

        $rows = Yii::app()->db->createCommand()->select("b.firm_id,a.amt_gt,a.amt_name")->from("sev_customer_info a")
            ->leftJoin("sev_customer_firm b","a.firm_cus_id = b.id")
            ->group("b.firm_id,a.amt_gt,a.amt_name")->order("a.amt_name asc,a.amt_gt desc")->queryAll();
        foreach ($rows as $row){
            $str = $row["amt_gt"] != 1?"或之前":"";
            $key = $row["amt_gt"].$row["amt_name"];
            //var_dump($key);die();
            $this->tableHeardList[$row["firm_id"]][$key] = $monthList[$row["amt_name"]].$str;
            if(in_array($row["firm_id"],$firmList)){
                $this->tableHeardList["branch"][$key] = $monthList[$row["amt_name"]].$str;
            }
        }
    }

    protected function getStrToNum($num){
        $arr = $this->listArr;
        if(count($arr)<=$num){
            $i = intval($num/count($arr))-1;
            $j = $num%count($arr);
            return $arr[$i].$arr[$j];
        }else{
            return $arr[$num];
        }
    }


    protected function setRowBody(){
        $rows = Yii::app()->db->createCommand()->select("a.*,c.client_code,c.customer_name,d.company_code")->from("sev_customer a")
            ->leftJoin("sev_company c","c.id = a.company_id")
            ->leftJoin("sev_group d","d.id = a.group_id")
            ->order("a.lcd desc")->queryAll();
        if($rows){
            $num = $this->row;
            foreach ($rows as $row){
                $this->setRowContent("A".$num,$row["client_code"]);//客戶編號
                $this->setRowContent("B".$num,$row["customer_name"]);//客戶名稱
                $this->setRowContent("C".$num,$row["company_code"]);//集團編號
                $column = $this->printAllFirmBody($row,$num);//欠款信息
                $str=$this->getStrToNum($column);
                $this->setRowContent($str.$num,$this->lbsMonth);//總公司欠款月數
                $column++;
                $str=$this->getStrToNum($column);
                $this->setRowContent($str.$num,$this->otherMonth);//係公司欠款月數
                $column++;

                foreach ($this->headListTwo() as $key=>$item){
                    $this->resetRow($key,$row);
                    $value = isset($row[$key])?$row[$key]:"";
                    $str=$this->getStrToNum($column);
                    $this->setRowContent($str.$num,$value);//係公司欠款月數
                    $column++;
                }


                $num++;
            }
        }
    }

    protected function resetRow($key,&$row){
        if(isset($row[$key])){
            if(in_array($key,array("staff_id","salesman_id"))){
                $row[$key]=StaffForm::getStaffNameToId($row[$key]);
            }
            if($key == "acca_lang"){
                $langList = FunctionForm::getAllLang();
                $row[$key]=$langList[$row['acca_lang']];
            }
            if($key == "group_type"){
                $row['group_type']=empty($row['group_type'])?Yii::t("several","not group"):Yii::t("several","is group");
            }
            if($key == "status_type"){
                $row['status_type']=Yii::t("code",$row['status_type']);
            }
        }
    }

    protected function getFirmAllAmt($cus_id){
        $arr = array();
        $rows = Yii::app()->db->createCommand()->select("b.firm_id,a.amt_gt,a.amt_name,a.amt_num")->from("sev_customer_info a")
            ->leftJoin("sev_customer_firm b","a.firm_cus_id = b.id")
            ->where("b.customer_id='$cus_id'")->queryAll();
        foreach ($rows as $row){
            $key = $row["amt_gt"].$row["amt_name"];
            $arr[$row["firm_id"]][$key] = $row["amt_num"];
        }
        return $arr;
    }

    protected function printAllFirmBody($arr,$row){
        $endNum = 3;
        $tableBody = array();
        $rows = Yii::app()->db->createCommand()->select("b.firm_id,a.amt_gt,a.amt_name,a.amt_num")->from("sev_customer_info a")
            ->leftJoin("sev_customer_firm b","a.firm_cus_id = b.id")
            ->where("b.customer_id=:id",array(":id"=>$arr["id"]))->queryAll();
        foreach ($rows as $list){
            $key = $list["amt_gt"].$list["amt_name"];
            $tableBody[$list["firm_id"]][$key] = $list["amt_num"];
        }
        foreach ($this->firmList as $key =>$item){
            if(key_exists($key,$this->tableHeardList)){
                $sum = 0;
                foreach ($this->tableHeardList[$key] as $amt=>$value){
                    $num = 0;
                    if(isset($tableBody[$key][$amt])){
                        $num = $tableBody[$key][$amt];
                        if($key != "branch"&&$item["type"]!=1){
                            if(!isset($tableBody["branch"][$amt])){
                                $tableBody["branch"][$amt] = 0;
                            }
                            $tableBody["branch"][$amt]+=$num;
                        }
                        $sum+=floatval($num);
                    }
                    if($num>0){
                        if($item["type"]==1){
                            $this->lbsMonth++;
                        }else{
                            $this->otherMonth++;
                        }
                    }
                    $str = $this->getStrToNum($endNum);
                    $this->setRowContent($str.$row,$num);//單個欠款
                    $endNum++;
                }
                $str = $this->getStrToNum($endNum);
                $this->setRowContent($str.$row,$sum);//合計
                $endNum++;
            }
        }
        return $endNum;
    }


    //繪製表格
    public function printTable($str){
        $styleArray = array(
            'borders' => array(
                'allborders' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        );
        $this->objActSheet->getStyle($str)->applyFromArray($styleArray);
    }

    //添加新的sheet
    public function addNewSheet($sheetName=""){
        $this->sheetNum++;
        $this->objPHPExcel->createSheet();
        $this->objActSheet = $this->objPHPExcel->setActiveSheetIndex($this->sheetNum);
        if(!empty($sheetName)){
            $this->objActSheet->setTitle($sheetName);
        }
    }


    //設置sheet的名字
    public function setSheetName($sheetName){
        $this->objPHPExcel->setActiveSheetIndexByName($sheetName);
        //$this->objPHPExcel->getActiveSheet()->setTitle( 'Invoice');
    }

    public function setRowExcel($date=""){
        if (empty($date)){
            $date = date("Y-m-d H:i:s");
        }else{
            $date = date("Y-m-d H:i:s",strtotime($date));
        }
        set_time_limit(0);

        $this->setExcelTop();

        $this->setRowHeard($date);

        $this->setRowBody();
    }

    //輸出excel表格
    public function outDownExcel($fileName){
        ob_end_clean();//清除缓冲区,避免乱码
        header("Content-Type: application/vnd.ms-excel; charset=utf-8");
        header('Content-Disposition: attachment;filename='.$fileName);
        header('Cache-Control: max-age=0');
        $objWriter = PHPExcel_IOFactory::createWriter($this->objPHPExcel,'Excel5');
        $objWriter->save('php://output');
        //exit;
    }

    //生成excel表格
    public function saveExcel($url){
        $url=Yii::app()->basePath."/../$url";
        if (file_exists($url)){
            unlink($url);
        }
        $excel = new PHPExcel_Writer_Excel2007();
        $excel->setPHPExcel($this->objPHPExcel);
        $excel->save($url);
    }
}
?>